### ISSUE TITLE
MRO Link: Completed RO never made to EMDECS

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#104]
See screen shot... associated to #93 

Sequence of events:

1. Started R05476, added one labour
2. Created Link R05477.
3. Added another labour and put on hold
4. Resumed R05476, completed.
5. Resumed R05477, completed.

**R05477 never made it EMDECS.** See log below:

![screen shot 2016-05-02 at 3 08 27 am](https://cloud.githubusercontent.com/assets/5666297/14948931/8b989130-1013-11e6-8d62-94a07bb1c66d.png)

**Comment by d3ssupport** [comment]
We will make changes to the audit log so it reflects the linked RO, originally was logged as parent RO

Regarding Emdecs we cannot test the link since there is problem with web service we are always get message in response "SYSTEM.ROUNI_RO_NUMBER_UK UNIQE CONSTRAIN" 

https://github.com/GCSO2/D3S-DEVELOPMENT/issues/230 

Please advise

**Comment by giovanicani** [comment]
As discusssed with Tufail, this may not be an issue at all. Let me look into it again.

**Comment by giovanicani** [comment]
working fine as designed. Thanks!
