### ISSUE TITLE
Cloud: RO Detail Screen Add Vendor selection field on the header

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#110]
Allow user to select from active vendors, when vendor is selected ask user if they want to notify vendor about the RO. Message (if REP_VENDORS_WV.EMAIL is not null):

Would you like to notify vendor via email (Internal Notes will be included on the email) ?

If yes, send an email to address(es) on REP_VENDORS_WV.EMAIL.

Subject: Assignment RO000123 - [Customer Name]
Body: Show internal Notes

**Comment by giovanicani** [comment]
Please add the drop down list into a new tab, called Sublet.

The sublet tab will have other fields in future releases, however for now just add the drop down list. The Sublet tab will go after the Labour & Parts Tab.

**Comment by d3sqa** [comment]
@giovanicani, how can the ven_id be saved against the RO as we currently does not have a field in REP_WORK_ORDERS table ?
UN-ASSIGNED and ASSIGNED status are also dependent upon this field #133 

Please provide your feedback

**Comment by giovanicani** [comment]
Please add new field VEN_ID NUMBER NULLABLE as a FK to VENDORS table.


UN-ASSIGNED and ASSIGNED status are also dependent upon this field  <--- **CORRECT**

**Comment by d3sqa** [comment]
Sublet tab has been added along with the sublet drop down. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15359316/299abdac-1d22-11e6-946e-3ee580d901ba.png)

Preferred vendors with * are displayed:

![image](https://cloud.githubusercontent.com/assets/13255706/15359336/41012bd4-1d22-11e6-8df0-57f81628ef97.png)

Please note that we are working on making the code and * in bold so that to enhance readibility

![image](https://cloud.githubusercontent.com/assets/13255706/15359422/aa67f2ec-1d22-11e6-82fa-3d831f2cb7f9.png)

![image](https://cloud.githubusercontent.com/assets/13255706/15359490/0ba7fb92-1d23-11e6-82e8-37edf69792ef.png)

**Comment by giovanicani** [comment]
Awesome. Thanks!

**Comment by d3sqa** [comment]
Vendor is now successfully saving against the RO on both Create and Edit forms. However, currently it can be changed only on the COMPLETE status. 
At Edit RO form, the vendor gets saved as soon as the user selects a vendor from the drop down.
Email is sent from the RO detail [Edit Form]

Ready to test in development environment

**Comment by giovanicani** [comment]
okay!
