### ISSUE TITLE
Cloud: Database change: OP_WORK_ORDER_PARTS (and _WV)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#128]
Please do the following changes to the table and view...

- Warranty_notes and notes from CLOB to VARCHAR2(2000)
- Remove estimate_qty field
- Add actual_qty NUMBER(7,2) NULLABLE
- Drop these 3 columns: LAST_INSERT_USERNAME, LAST_UPDATE_USERNAME, LAST_INSERT_DATE

What is the difference between actual_qty and charge_qty ?

**actual_qty** = quantity selected by the mechanic on the tablet. **This quantity will be used to issue the part**. If quantity used is for example 2 for filter, it means that the mechanic used 2 filters and removed 2 from his inventory.

**charge_qty** = **quantity to be charged to customer**. Initially when completed from the tablet, this quantity is the same as actual_qty, however the person approving the RO can change this, for instance change from 2 to 0. This will allow still issueing 2 from inventory, but charging ZERO to customer.

On the other way, when RO done by a sublet (vendor), actual may be zero - no part used from Trailcon, however charge can be a different quantity, like 3.

# Total Charge is: charge_qty * item_charge.

**Comment by d3sqa** [comment]
Update:

Above mentioned changes has been done to the table
Inline editing feature has been incorporated on Charge QTY field at part's grid

We are now working on the following:

Actual Qty is the quantity entered from the mobile application and charge qty should reflect same value as actual when the RO gets completed. 

One question: Should we display 'Total Charge' column on the Part's grid ?

**Comment by giovanicani** [comment]
Yes, please total charge per line is required.
Also total part charge ($) for RO is also required at the bottom.

**Comment by d3sqa** [comment]
Actual QTY is now mapped with the part QTY being entered from mobile. Charge QTY will have same value as the actual QTY. Charge QTY can also be inline edited at cloud. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/15319224/3f0178aa-1c43-11e6-8ef4-ca34cf6dfa29.png)

![image](https://cloud.githubusercontent.com/assets/13255706/15319898/f17e0cde-1c46-11e6-857f-653a061b746c.png)

Total Charge field has been added at the cloud against each part. Also, the total sum of Total Charge has been displayed below the part's grid. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15318921/beb7e52c-1c41-11e6-803c-4ca1391b4d77.png)

Question: If a unit charge is not defined against a part, what should be done in this case ? Should we display 0 ? Because it has an impact on the Total Charge. If left blank, how will the multiplication with charge_qty occur ?

**Comment by giovanicani** [comment]
as discussed leave it 0 if charge does not exist.
