### ISSUE TITLE
Cloud: Receiving Listing, details not opening on a new tab

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#74]
When double clicking on the Receiving Listing, details should open on a new tab like it happens when "Create Receiving".

When pressing Save & Close or Close, it should (alert if any changes not saved and) close the browser tab, like it is done with PO.

Please make sure that all Inventory screens have this behaviour, to keep it consistent.

**Comment by d3sqa** [comment]
@giovanicani,
If the user clicks Save & Close, is there any need to prompt an alert ? Because the changes are actually getting saved and no data loss will occur. 

Please note when the user clicks on Close with the forms having unsaved changes, the user is already prompted with a warning.

Double clicking a record on listing will open the detail screen in a new tab - Done on all (PO, Receiving, Transfer and Physical Count)

**Comment by giovanicani** [comment]
If changes are saved, then no need to prompt alert. Will close ticket. Thanks!
